# Generated by Django 2.1.4 on 2019-02-01 20:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20190201_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='number_of_places',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='booking',
            name='Date_From',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 1, 21, 41, 20, 517927)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='Date_To',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 1, 21, 41, 20, 517927)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'active'), ('EXPIRED', 'expired'), ('RESERVED', 'reserved'), ('CANCELLED', 'cancelled')], default='ACTIVE', max_length=10),
        ),
    ]
