# Generated by Django 2.1.4 on 2019-02-01 20:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20190201_2141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='number_of_places',
            new_name='number_of_cars',
        ),
        migrations.AlterField(
            model_name='booking',
            name='Date_From',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 1, 21, 42, 15, 652271)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='Date_To',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 1, 21, 42, 15, 652271)),
        ),
    ]
