# Generated by Django 2.1.4 on 2019-02-02 00:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20190201_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='parking',
        ),
        migrations.AddField(
            model_name='booking',
            name='parking_f',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='parking_f', to='pages.Parking'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='Date_From',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 2, 1, 56, 59, 413917)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='Date_To',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 2, 1, 56, 59, 413917)),
        ),
    ]
